# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-26 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrouser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_surname', models.CharField(max_length=50)),
                ('add_email', models.EmailField(max_length=100, verbose_name='Add email')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
