# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-26 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrouser', '0003_userprofile_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
