# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrouser', '0004_auto_20170126_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_account', to=settings.AUTH_USER_MODEL, verbose_name='user-account'),
        ),
    ]
