// Generated by CoffeeScript 1.8.0
module.exports = (function() {
  var $, Backbone, Collection, Model, View;
  $ = require('jquery');
  Backbone = require('backbone');
  Backbone.$ = $;
  Model = require('./model/model.js');
  Collection = require('./collection/collection.js');
  View = require('./view/view.js');
  return $(function() {
    var collection, model, view;
    model = new Model;
    collection = new Collection;
    view = new View({
      'collection': collection
    });
    console.log('reseted');
    return window.app = view;
  });
})();
