# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-08 19:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20170108_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceweatherdata',
            name='activity_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spaceweatherdata',
            name='grabbed_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 8, 19, 57, 10, 66491, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='grabbed_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 8, 19, 57, 10, 65879, tzinfo=utc)),
        ),
    ]
