# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-23 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoonZodiac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('zodiac', models.PositiveSmallIntegerField(choices=[(1, 'Овен'), (2, 'Телец'), (3, 'Близнецы'), (4, 'Рак'), (5, 'Лев'), (6, 'Дева'), (7, 'Весы'), (8, 'Скорпион'), (9, 'Стрелец'), (10, 'Козерог'), (11, 'Водолей'), (12, 'Рыбы')])),
            ],
        ),
        migrations.CreateModel(
            name='SummaryFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('serves_pizza', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ZodiacContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='media/zodiac_imgs/%Y/%m/%d/')),
                ('zodiac_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_zodiac', to='engine.MoonZodiac')),
            ],
        ),
        migrations.AddField(
            model_name='moonzodiac',
            name='moon_zodiac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factor_zodiac', to='engine.SummaryFactor'),
        ),
    ]
