# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-11 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoonZodiac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('zodiac', models.CharField(choices=[(1, '\u041e\u0432\u0435\u043d'), (2, '\u0422\u0435\u043b\u0435\u0446'), (3, '\u0411\u043b\u0438\u0437\u043d\u0435\u0446\u044b'), (4, '\u0411\u043b\u0438\u0437\u043d\u0435\u0446\u044b'), (5, '\u0411\u043b\u0438\u0437\u043d\u0435\u0446\u044b'), (6, '\u0411\u043b\u0438\u0437\u043d\u0435\u0446\u044b'), (7, '\u0411\u043b\u0438\u0437\u043d\u0435\u0446\u044b'), (8, '\u0411\u043b\u0438\u0437\u043d\u0435\u0446\u044b'), (9, '\u0411\u043b\u0438\u0437\u043d\u0435\u0446\u044b'), (10, '\u0411\u043b\u0438\u0437\u043d\u0435\u0446\u044b'), (11, '\u0411\u043b\u0438\u0437\u043d\u0435\u0446\u044b'), (12, '\u0411\u043b\u0438\u0437\u043d\u0435\u0446\u044b')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('moon_zodiac', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='engine.MoonZodiac')),
                ('serves_hot_dogs', models.BooleanField(default=False)),
                ('serves_pizza', models.BooleanField(default=False)),
            ],
        ),
    ]
