# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-11 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20170111_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moonzodiac',
            name='zodiac',
            field=models.PositiveSmallIntegerField(choices=[(1, '\u041e\u0432\u0435\u043d'), (2, '\u0422\u0435\u043b\u0435\u0446'), (3, '\u0411\u043b\u0438\u0437\u043d\u0435\u0446\u044b'), (4, '\u0420\u0430\u043a'), (5, '\u041b\u0435\u0432'), (6, '\u0414\u0435\u0432\u0430'), (7, '\u0412\u0435\u0441\u044b'), (8, '\u0421\u043a\u043e\u0440\u043f\u0438\u043e\u043d'), (9, '\u0421\u0442\u0440\u0435\u043b\u0435\u0446'), (10, '\u041a\u043e\u0437\u0435\u0440\u043e\u0433'), (11, '\u0412\u043e\u0434\u043e\u043b\u0435\u0439'), (12, '\u0420\u044b\u0431\u044b')]),
        ),
    ]
