# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-24 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20170124_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zodiaccontent',
            old_name='zodiac_content',
            new_name='mzcontent',
        ),
    ]
