# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-21 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20170111_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZodiacContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='media/zodiac_imgs/%Y/%m/%d/')),
                ('zodiac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_zodiac', to='engine.MoonZodiac')),
            ],
        ),
    ]
