# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-23 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_zodiaccontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='moon_zodiac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='factor_zodiac', serialize=False, to='engine.MoonZodiac'),
        ),
    ]
