# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-23 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20170123_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='moon_zodiac',
        ),
        migrations.RemoveField(
            model_name='factor',
            name='serves_hot_dogs',
        ),
        migrations.AddField(
            model_name='factor',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factor',
            name='name',
            field=models.CharField(default='factor name', max_length=50),
        ),
        migrations.AddField(
            model_name='moonzodiac',
            name='moon_zodiac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factor_zodiac', to='engine.Factor'),
        ),
    ]
