# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-24 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_moonday'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoonDayContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='media/zodiac_imgs/%Y/%m/%d/')),
                ('mdcontent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mday_content', to='engine.MoonDay')),
            ],
        ),
    ]
