# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-24 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_moondaycontent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZodiacContent',
            new_name='MoonZodiacContent',
        ),
    ]
