# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-24 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_auto_20170124_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryfactor',
            name='marked_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
