# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-26 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrouser', '0003_userprofile_account'),
        ('engine', '0009_summaryfactor_marked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_profile', to='astrouser.UserProfile')),
            ],
        ),
    ]
