# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_auto_20170127_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='todo',
            new_name='dtp1',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='todata',
            new_name='dtp2',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='reminder',
            new_name='dtp3',
        ),
    ]
