# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_auto_20170127_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='dtp1',
            new_name='timezone_name',
        ),
        migrations.RemoveField(
            model_name='place',
            name='dtp2',
        ),
        migrations.RemoveField(
            model_name='place',
            name='dtp3',
        ),
        migrations.RemoveField(
            model_name='place',
            name='timezone',
        ),
    ]
