# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0016_auto_20170201_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moonzodiac',
            name='mzodiac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_mzodiac', to='engine.SummaryFactor'),
        ),
        migrations.AlterField(
            model_name='moonzodiaccontent',
            name='mzcontent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_mzcontent', to='engine.MoonZodiac'),
        ),
    ]
