# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_auto_20170203_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='elevation',
            field=models.FloatField(blank=True, default=3.0, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='horizon',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='pressure',
            field=models.FloatField(blank=True, default=1010.0, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='temperature',
            field=models.FloatField(blank=True, default=25.0, null=True),
        ),
    ]
