# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0020_auto_20170203_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moonzodiac',
            old_name='mzodiac',
            new_name='summaryfactor',
        ),
    ]
