# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0021_auto_20170207_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moonday',
            old_name='mday',
            new_name='summaryfactor',
        ),
        migrations.RenameField(
            model_name='moondaycontent',
            old_name='mdcontent',
            new_name='moonday',
        ),
        migrations.RenameField(
            model_name='moonzodiaccontent',
            old_name='mzcontent',
            new_name='moonzodiac',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='profile',
            new_name='userprofile',
        ),
    ]
