# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0022_auto_20170207_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_observer', to='astrouser.UserProfile'),
        ),
    ]
