# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0023_auto_20170207_2219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Observer',
        ),
    ]
