# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0024_auto_20170207_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moondaycontent',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='moonday',
            name='quality',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='moondaycontent',
            name='source',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='moondaycontent',
            name='symbol',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='moondaycontent',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/moonday_imgs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='moondaycontent',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
