# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0025_auto_20170208_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moondaycontent',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
