# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 05:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0026_auto_20170208_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summaryfactor',
            old_name='serves_pizza',
            new_name='special_case',
        ),
        migrations.AddField(
            model_name='summaryfactor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='summaryfactor',
            name='moon_lat',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AddField(
            model_name='summaryfactor',
            name='moon_lng',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AddField(
            model_name='summaryfactor',
            name='moon_phase',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
