# Generated by Django 2.0.1 on 2018-01-19 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astrouser', '0005_auto_20170203_1757'),
        ('engine', '0028_auto_20180103_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('began_at', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField()),
                ('mark_day_as_a_whole', models.PositiveSmallIntegerField(choices=[(1, 'awfully'), (2, 'bad'), (3, 'normally'), (4, 'good'), (5, 'excellent')])),
                ('mark_body', models.PositiveSmallIntegerField(choices=[(1, 'awfully'), (2, 'bad'), (3, 'normally'), (4, 'good'), (5, 'excellent')])),
                ('mark_emotions', models.PositiveSmallIntegerField(choices=[(1, 'awfully'), (2, 'bad'), (3, 'normally'), (4, 'good'), (5, 'excellent')])),
                ('mark_intelligence', models.PositiveSmallIntegerField(choices=[(1, 'awfully'), (2, 'bad'), (3, 'normally'), (4, 'good'), (5, 'excellent')])),
                ('description', models.CharField(max_length=50)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sensations', to='astrouser.UserProfile')),
            ],
        ),
    ]
