# Generated by Django 2.0.1 on 2018-01-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrouser', '0005_auto_20170203_1757'),
        ('engine', '0029_sensations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensations',
            new_name='Sensation',
        ),
    ]
