# Generated by Django 2.0.1 on 2018-01-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0030_auto_20180119_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensation',
            name='description',
        ),
        migrations.AddField(
            model_name='sensation',
            name='details',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sensation',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
