# Generated by Django 2.0.1 on 2018-01-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0031_auto_20180119_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensation',
            name='mark_body',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'awfully'), (2, 'bad'), (3, 'normally'), (4, 'good'), (5, 'excellent')]),
        ),
        migrations.AlterField(
            model_name='sensation',
            name='mark_day_as_a_whole',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'awfully'), (2, 'bad'), (3, 'normally'), (4, 'good'), (5, 'excellent')]),
        ),
        migrations.AlterField(
            model_name='sensation',
            name='mark_emotions',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'awfully'), (2, 'bad'), (3, 'normally'), (4, 'good'), (5, 'excellent')]),
        ),
        migrations.AlterField(
            model_name='sensation',
            name='mark_intelligence',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'awfully'), (2, 'bad'), (3, 'normally'), (4, 'good'), (5, 'excellent')]),
        ),
    ]
