# Generated by Django 2.0.1 on 2018-01-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0033_auto_20180119_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensation',
            name='began_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensation',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensation',
            name='mark_body',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'awfully'), (2, 'bad'), (3, 'normally'), (4, 'good'), (5, 'excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='sensation',
            name='mark_day_as_a_whole',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'awfully'), (2, 'bad'), (3, 'normally'), (4, 'good'), (5, 'excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='sensation',
            name='mark_emotions',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'awfully'), (2, 'bad'), (3, 'normally'), (4, 'good'), (5, 'excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='sensation',
            name='mark_intelligence',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'awfully'), (2, 'bad'), (3, 'normally'), (4, 'good'), (5, 'excellent')], null=True),
        ),
    ]
